name = "Jade's Parity Plus"
author = "jadelily18"
version = "2.3.0+1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a4c30e6369a0643bbc10e0d51a65ff7e6339f5bd0138f77a2aa60c84eefaae2"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"

[options]
acceptable-game-versions = ["1.19.3", "1.19.4"]
